repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
        args:
          - '--assume-in-merge'
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: sort-simple-yaml
      - id: trailing-whitespace
        exclude: \.ambr$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.3"
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"
        exclude: src/any_agent/vendor
      - id: ruff-format

  - repo: local
    # Thanks to https://jaredkhan.com/blog/mypy-pre-commit
    # We do not use pre-commit/mirrors-mypy,
    # as it is difficult to configure to run
    # with the dependencies correctly installed.
    hooks:
      - id: mypy
        name: mypy
        entry: "./scripts/run-mypy.sh"
        language: python
        language_version: python3.13
        additional_dependencies:
          - mypy==1.15.0
          - pip
          - types-requests
          - types-pyyaml
        types: [python]
        # use require_serial so that script is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
        exclude: CODE_OF_CONDUCT.md|tests/assets
