site_name: any-agent

repo_url: https://github.com/mozilla-ai/any-agent
repo_name: any-agent

nav:
  - Intro: index.md
  - Agents:
    - Defining and Running Agents: agents/index.md
    - Frameworks:
      - Agno: agents/frameworks/agno.md
      - Google ADK: agents/frameworks/google_adk.md
      - Langchain: agents/frameworks/langchain.md
      - LlamaIndex: agents/frameworks/llama_index.md
      - OpenAI Agents SDK: agents/frameworks/openai.md
      - smolagents: agents/frameworks/smolagents.md
      - TinyAgent: agents/frameworks/tinyagent.md
    - Tools: agents/tools.md
  - Tracing: tracing.md
  - Evaluation: evaluation.md
  - Serving: serving.md
  - Cookbook:
      - Your First Agent: cookbook/your_first_agent.ipynb
      - MCP Agent: cookbook/mcp_agent.ipynb
      - Serve with A2A: cookbook/serve_a2a.ipynb
      - Use an Agent as a tool for another agent (A2A): cookbook/a2a_as_tool.ipynb
  - API Reference:
    - Agent: api/agent.md
    - Config: api/config.md
    - Tools: api/tools.md
    - Tracing: api/tracing.md
    - Logging: api/logging.md

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: images/any-agent-logo-mark.png
  favicon: images/any-agent_favicon.png
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit

extra_css:
  - assets/custom.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- include-markdown
- mkdocs-jupyter:
      no_input: false
      show_input: true
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          heading_level: 3

edit_uri: edit/main/docs/
