name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install
        run: |
          uv sync --group tests --extra all --extra serve

      - name: Run Documentation tests
        run: pytest -v tests/docs

      - name: Run Unit tests
        run: pytest -v tests/unit

      - name: Run Snapshot tests
        run: pytest -v tests/snapshots

      - name: Run Integration tests (parallel with xdist)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          ANY_AGENT_INTEGRATION_TESTS: TRUE
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/integration -d --tx '4*popen//python=python'
