name: Cookbook Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/cookbook/**'
  workflow_dispatch:

jobs:
  run-cookbook-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install
        run: |
          uv sync --group tests --extra all --extra a2a

      - name: Run Cookbook Tests
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: |
          pytest tests/cookbooks -v -n 4
