name: Tests for Docs

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  run-docs-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install
        run: |
          uv sync --group tests --extra all --extra a2a

      - name: Run Documentation tests
        run: pytest -v tests/docs
